---

- name: Clone | Packages
  package: name=git state=latest

- name: Create | Directory | {{ clone_dir_name }}
  file:
    path: '{{ base_dir }}/python/{{ clone_dir_name }}'
    state: directory
    mode: '0755'

- name: Clone | Git | Repo
  git:
    repo: "{{ clone_from_url }}"
    dest: "{{ base_dir }}/python/{{ clone_dir_name }}"
    update: "yes"
    force: true

