---

- name: Clone | Packages
  package: name=git state=latest

- name: Copy | Deploy key
  copy:
    content: "{{ item.value.clone_deploy_key }}"
    dest: "{{ item.value.base_path }}/id_deploy_key"
    owner: tryton
    group: tryton
    mode: "0600"
  #no_log: true
  when: [ item.value.clone_is_private ] 

- name: Clone | Git | Repo
  git:
    repo: "{{ item.value.clone_from_url }}"
    dest: "{{ item.value.base_path }}/python/{{ item.value.clone_dir_name }}"
    update: yes
    accept_hostkey: yes
    key_file: "{{ item.value.base_path }}/id_deploy_key"
  become_user: "{{ item.value.user }}"

- name: Create | symbolic link 
  file:
    src: "{{ item.value.base_path }}/python/{{ item.value.clone_dir_name }}/{{ clone_sym_link_module }}"
    dest: "{{ item.value.base_path }}/python/lib/{{ python_version }}/site-packages/trytond/modules/{{ clone_sym_link_module }}"
    state: link