---

- name: Clone | Packages
  package: name=git state=latest

- name: Copy | Deploy key
  copy:
    content: "{{ tryton_clone_deploy_key }}"
    dest: "{{ tryton_base_path }}/id_deploy_key"
    owner: tryton
    group: tryton
    mode: "0600"
  no_log: true

- name: Clone | Git | Repo
  git:
    repo: "{{ tryton_clone_from_url }}"
    dest: "{{ tryton_base_path }}/python/{{ tryton_clone_dir_name }}"
    update: yes
    accept_hostkey: yes
    key_file: "{{ tryton_base_path }}/id_deploy_key"
  become_user: tryton
