---

- name: Tryton | Conf 
  template:
    src: trytond.conf.j2
    dest: "{{ item.value.base_path }}/python/trytond.conf"  
  become_user: "{{ item.value.user }}"
  with_dict: "{{ tryton_versions }}" 