---

- name: Install | Dependencies
  apt:
    name:
      - python
      - python-dev
      - gcc
      - libpq-dev
      - virtualenv
    state: present
    update_cache: yes

- name: Upgrade | Pip
  pip:
    name:
      - pip
      - virtualenv
    state: latest

- name: Create | User | Tryton
  user:
    name: tryton
    create_home: yes
    home: "{{ tryton_base_path }}"
    shell: /bin/false
    state: present

- name: Pip | Template | Requirements
  template:
    src: requirements.txt.j2
    dest: "{{ tryton_base_path }}/requirements.txt"
    owner: tryton

- name: Pip | Tryton packages
  pip: 
    chdir: "{{ tryton_base_path }}"
    requirements: requirements.txt
    virtualenv: "{{ tryton_base_path }}/python"
    virtualenv_python: "{{ tryton_python_version }}"
    state: "{{ tryton_python_state }}"
  become_user: tryton