---

- include_tasks: dependencies.yml

- include_tasks: configuration.yml

- include_tasks: clone_repository.yml
  when: [ item.value.clone_from_repository ] 
  with_dict: "{{ tryton_versions }}"

- include_tasks: tryton_sao.yml
  when: [ item.value.sao_install ]
  with_dict: "{{ tryton_versions }}"

- include_tasks: systemd_conf.yml
  when: [ item.value.systemd_service is defined ]
  with_dict: "{{ tryton_versions }}"
