---

- include_tasks: dependencies.yml

- include_tasks: configuration.yml

- include_tasks: clone_repository.yml
  when: '{{ item.value.clone_from_repository }} | bool' 
  with_items: tryton_versions

- include_tasks: tryton_sao.yml
  when: tryton_sao_install | bool