---

- include_tasks: dependencies.yml

- include_tasks: configuration.yml

- include_tasks: clone_repository.yml
  when: clone_from_repository | bool

  
- include_tasks: tryton_sao.yml
  when: tryton_sao_install | bool