---

- name:  Tryton | Systemd template
  template:
    src: systemd.conf.j2
    dest: "/etc/systemd/system/{{ item.value.systemd_service }}.service"
    owner: "{{ item.value.user }}"
    mode: 0755

- name: Tryton | Systemd reload services
  command: systemctl daemon-reload

- name: Tryton | Ensure services are started and enabled on boot
  service:
    name: "{{ item.value.systemd_service }}.service"
    state: started
    enabled: yes
