---

- name: Tryton-sao | Nodesource apt key
  apt_key:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
    id: "68576280"
    state: present

- name: Tryton-sao | repositories for Node.js
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb https://deb.nodesource.com/node_{{ item.value.nodejs_version }} {{ ansible_distribution_release }} main"
    - "deb-src https://deb.nodesource.com/node_{{ item.value.nodejs_version }} {{ ansible_distribution_release }} main"
  register: node_repo

- name: Tryton-sao | Update apt cache if repo was added
  apt: update_cache=yes
  when: node_repo.changed

- name: Tryton-sao | Install Node.js and npm 
  apt:
    name: "nodejs={{ item.value.nodejs_version|regex_replace('x', '') }}*"
    state: present

- name: Tryton-sao | Download sao
  unarchive:
    src: "https://github.com/tryton/sao/archive/{{ item.value.sao_version }}.tar.gz"
    dest: "{{ item.value.sao_dest }}/"
    remote_src: yes
  become_user: "{{ item.value.user }}"
  
- name: Tryton-sao | npm install
  npm:
    path: "{{ item.value.sao_dest }}/sao-{{ item.value.sao_version }}"
    executable: /usr/bin/npm
    state: present

- name: Tryton-sao | npm Bower install
  npm:
    name: bower
    global: yes
    state: present

- name: Tryton-sao | Bower install
  bower:
    path: "{{ item.value.sao_dest }}/sao-{{ item.value.sao_version }}"

- name: Tryton-sao | npm Grunt install
  npm:
    name: grunt
    global: yes
    state: present

- name: Tryton-sao | Grunt
  shell: 
    cmd: grunt
    chdir: "{{ item.value.sao_dest }}/sao-{{ item.value.sao_version }}"